id: A1F56F5F1
title: 'Shower of Indestructible Splendour: A Self-Initiation for the Guru Practice
  of the Vidyādhara Assembly, from the Heart-Essence of the Vast Expanse'
type: translation
pechas:
- ID66131D8
- I8F661934
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:36:06.503224
  last_modified_at: 2023-01-04 11:36:06.503237
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  ID66131D8/7BC5: '4023'
  I8F661934/DA55: '4023'
